queue_rules:
  - name: default
    conditions:
      - "check-success=check / terraform-check"
pull_request_rules:
  - name: automatic merge for Scala Steward
    conditions:
      - author=tna-da-bot
      - "check-success=check / terraform-check"
      - or:
          - files=build.sbt
          - files~=^(!?project/)
    actions:
      review:
        type: APPROVE
        message: Automatically approving Scala Steward updates
      queue:
        name: default
