name: Backend checks performance release
on:
  pull_request:
    types:
      - closed
permissions:
  id-token: write
  contents: write
env:
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'main' && github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - id: build
        run: |
          git config --global user.email 181243999+tna-da-bot@users.noreply.github.com
          git config --global user.name tna-da-bot
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
          sbt 'release with-defaults'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - run: |
          gh release create --generate-notes ${{ steps.build.outputs.latest-tag}} target/universal/performance.tgz
          gh pr create --fill --label 'Version bump'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        with:
          message: "*Backend check performance* Created release for version ${{ steps.build.outputs.latest-tag}}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
