name: Backend checks performance release
on:
  pull_request:
    types:
      - closed
permissions:
  id-token: write
  contents: write
env:
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master' && github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
    steps:
      - uses: actions/checkout@v3
      - id: build
        run: |
          git config --global user.email digitalpreservation@nationalarchives.gov.uk
          git config --global user.name tna-digital-archiving-jenkins
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
          sbt 'release with-defaults'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - run: |
          gh release create --generate-notes ${{ steps.build.outputs.latest-tag}} target/universal/performance.tgz
          gh pr create --fill --label 'Version bump'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        with:
          message: "*Backend check performance* Created release for version ${{ steps.build.outputs.latest-tag}}"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
