name: Upsert `scala-steward-dependencies` branch

on:
  push:
    branches: main
jobs:
  upsert-develop-branch:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Rebase `scala-steward-dependencies` branch to latest `origin/main`
    steps:
      - name: Checkout scala-steward-dependencies branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: scala-steward-dependencies
          fetch-depth: 0
      - name: Rebase `scala-steward-dependencies` branch to latest `origin/main`
        run: |
            git config user.email 181243999+tna-da-bot@users.noreply.github.com
            git config user.name tna-da-bot
            git rebase origin/main
            git push -f -u origin scala-steward-dependencies
